# Generated by Django 2.1.5 on 2019-08-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAuthor',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('sex', models.CharField(db_column='sex', default='', max_length=3, null=True)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'infoauthor',
            },
        ),
        migrations.CreateModel(
            name='InfoBook',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('isbn', models.CharField(db_column='isbn', max_length=255, unique=True)),
                ('num', models.PositiveIntegerField(db_column='num', default=0)),
                ('summary', models.TextField(db_column='summary')),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.InfoAuthor')),
            ],
            options={
                'db_table': 'infobook',
            },
        ),
        migrations.CreateModel(
            name='InfoBookLb',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('lbdm', models.CharField(db_column='lbdm', max_length=20, unique=True)),
                ('lbmc', models.CharField(db_column='lbmc', max_length=255)),
            ],
            options={
                'db_table': 'infobooklb',
            },
        ),
        migrations.CreateModel(
            name='InfoPublisher',
            fields=[
                ('id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('city', models.CharField(db_column='city', max_length=255, null=True)),
            ],
            options={
                'db_table': 'infopublisher',
            },
        ),
        migrations.AddField(
            model_name='infobook',
            name='lbID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.InfoBookLb'),
        ),
        migrations.AddField(
            model_name='infobook',
            name='pubid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.InfoPublisher'),
        ),
    ]
